# Generated by Django 4.2.2 on 2023-07-04 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_moderno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinho',
            old_name='cliente',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='cliente',
            new_name='usuario',
        ),
    ]
