# Generated by Django 4.2.2 on 2023-07-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_moderno', '0002_rename_cliente_carrinho_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/mercado_moderno/images/'),
        ),
    ]
