# Generated by Django 4.2.2 on 2023-07-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_moderno', '0002_alter_produto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='desconto',
        ),
    ]
